version: '2'
services:
  kubernetes:
    image: nginx:alpine
    volumes:
      - ./example/compose/nginx/kubernetes/nginx.conf:/etc/nginx/nginx.conf
      - ./example/compose/nginx/kubernetes/ssl:/etc/ssl
    networks:
      authelianet:
        aliases:
          - public.example.com
          - secure.example.com
          - login.example.com
          - admin.example.com
          - dev.example.com
          - mail.example.com
        # Set the IP to be able to query on port 443
        ipv4_address: 192.168.240.100
